[build]
  command = "sh deploy.sh"
  publish = "/deploy"
  base = "/"

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
