backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

media_folder: "images/uploads"

collections:
  - name: "issues"
    label: "Issues"
    label_singular: "Issue"
    folder: "_posts/issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cause", name: "cause", widget: "relation", collection: "issues", value_field: "{{slug}}", display_fields: ["title"], search_fields: ["title"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "risks"
    label: "Risks"
    label_singular: "Risk"
    folder: "_posts/risks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "improvements"
    label: "Improvements"
    label_singular: "Improvement"
    folder: "_posts/improvements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Solves", name: "solves", widget: "relation", collection: "issues", value_field: "{{slug}}", display_fields: ["title"], search_fields: ["title"], multiple: true }

