
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.BOT_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - run: npm ci
    - run: npm run verify
    - run: cd website && npm ci && npm run build
